apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: roboshop-cart
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cart
  endpoints:
  - port: http
    interval: 15s